[theme]
primaryColor = "#237d86"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#edf2f7"
textColor = "#172c43"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 2
